name="altrp-site"
compatibility_date="2025-10-13"
compatibility_flags=["nodejs_compat"]

pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "altrp-site-db"
database_id = "303ce694-3be1-436a-a36d-8cdf6ee03504"